# Generated by Django 3.1.5 on 2021-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210218_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='New Room', max_length=200, null=True)),
                ('user', models.CharField(max_length=500)),
            ],
        ),
    ]
